HOOK_WORDS = [
    "Now", "Instant", "Limited", "Hurry", "Last Chance", "Today", "Immediately",
    "Final", "Only", "Left", "Almost Gone", "Don't Miss", "Final Call",
    "Time-Sensitive", "Act Fast", "Running Out", "Ending Soon", "One-Time",
    "Exclusive Offer", "While Supplies Last", "Closing Soon", "Deadline",
    "Countdown", "Vanishing", "Disappearing", "Fading","Love", "Hate", "Fear", "Joy", "Anger", "Surprise", "Desire", "Hope",
    "Pride", "Guilt", "Shame", "Excitement", "Passion", "Longing", "Nostalgia",
    "Thrill", "Awe", "Empowerment", "Confidence", "Security", "Belonging",
    "Freedom", "Relief", "Satisfaction", "Delight", "Gratitude", "Trust",
    "Curiosity", "Wonder", "Inspiration", "Motivation","Exclusive", "VIP", "Elite", "Premium", "Luxury", "Private",
    "Members-Only", "Invite-Only", "Rare", "One-of-a-Kind", "Custom",
    "Tailored", "Handpicked", "Select", "Chosen", "Privileged",
    "High-End", "Top-Tier", "Superior", "Unmatched", "Legendary","Get", "Grab", "Claim", "Start", "Join", "Try", "Buy", "Download",
    "Subscribe", "Click", "Act", "Do It", "Seize", "Take", "Go", "Move",
    "Rush", "Jump", "Dive", "Explore", "Unlock", "Discover", "Access",
    "Secure", "Reserve", "Book", "Order", "Sign Up", "Register",
    "Apply", "Engage","Free", "Save", "Boost", "Transform", "Revolutionize", "Upgrade",
    "Improve", "Enhance", "Maximize", "Optimize", "Simplify", "Effortless",
    "Easy", "Fast", "Quick", "Powerful", "Effective", "Proven",
    "Guaranteed", "Risk-Free", "Hassle-Free", "Seamless", "Painless",
    "Smart", "Innovative","Stunning", "Vibrant", "Dazzling", "Breathtaking", "Eye-Catching",
    "Loud", "Silent", "Melodic", "Crisp", "Smooth", "Soft", "Rough",
    "Velvety", "Grip", "Heartwarming", "Thrilling", "Awe-Inspiring",
    "Nostalgic", "Empowering", "Irresistible","As Seen On", "Loved by", "Trusted by", "Raved About", "Fan Favorite",
    "Top-Rated", "Award-Winning", "#1", "Best-Selling", "Most Popular",
    "Highly Recommended", "Endorsed", "Certified", "Verified", "Proven",
    "Beloved", "Acclaimed", "Celebrated", "Praised", "Admired","Struggling", "Tired", "Frustrated", "Overwhelmed", "Fed Up", "Stuck",
    "Lost", "Confused", "Broken", "Fix", "Solve", "Cure", "Eliminate",
    "Banish", "Relieve", "Heal", "Repair", "Restore", "Renew", "Rescue",
    "Overcome", "Survive", "Thrive", "Conquer","Secret", "Hidden", "Unveiled", "Mystery", "Revealed", "Discover",
    "What If", "Imagine", "Picture This", "Ever Wondered", "The Truth About",
    "Little-Known", "Forgotten", "Untold", "Shocking", "Surprising",
    "Unbelievable", "Mind-Blowing", "Jaw-Dropping", "Unimaginable","But", "However", "Yet", "Instead", "Unlike", "While", "Although",
    "Though", "Despite", "Except", "Unless", "Until", "Rather",
    "Meanwhile", "Conversely","You", "Your", "Yours", "Just for You", "Customized",
    "Designed for You", "Made for You", "Only You", "Handpicked for You"
]